events {
    worker_connections 256;
}
http {
    server {
        listen 8080;

        location /health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 'ok';
        }

        # बाकी सगळे requests block
        location / {
            return 444;
        }
    }
}
